### ISSUE TITLE
Text field of label is too narrow

### ISSUE THREAD

**Issue by rubycoder** [AndyObtiva/glimmer-dsl-swt#15]
This program has a 2 column grid layout.  Each row has a radio button and a label.  The text displayed in the label is supposed to start at 1, and increment every second... 2, 3, 4, ... 9.  So far, all this works perfectly.  But the next second it displays 1 rather than the expected 10. 1 is displayed for the next 10 seconds, then 2 is displayed for 10 seconds, then 3, etc.

What appears to be happening is that the width of the label is only 1 character.  So this works for 1, 2, ... 9, but for 10, 11, etc. only the first digit is displayed.

I can work around this by padding the label text with blanks so it is always the same length, but it doesn't seem that I should need to do this.  In getting the padding working, I thought I'd only have to pad an empty string with 8 blanks, as this would then be the same string length as '00:00:00'.  Trying this, only about the first half of the string was visible "00:0".  It requires about 15 blanks to make sure that the entire '00:00:00' will be visible.  So it seems that the issue is not the length in characters of the label, but the width in pixels of the label.  (I just confirmed this by running on Catalina.  The font is different, and when it attempts to display "10", I see the "1" and just a few pixels of the "0".)

Thank you for any advice.

glimmer 2.5.1, glimmer-dsl-swt 4.21.2.4, jruby 9.3.1.0, JDK 16.0.2, x86_64 on Windows 7 Professional SP 1
glimmer 2.5.1, glimmer-dsl-swt 4.21.2.4, jruby 9.3.0.0. x86_64 on Mac Catalina 10.14.6

(file name changed from .rb to .txt)

[text_field_width_issue.txt](https://github.com/AndyObtiva/glimmer-dsl-swt/files/7610481/text_field_width_issue.txt)

**Comment by AndyObtiva** [comment]
Funny, I just updated the docs today because several people reported having your issue without realizing it is as simple to fix as adding layout options for fill space horizontally.

Here is the code with one extra line to specify `grid_layout`-related `layout_data :fill, :center, true, false`, indicating you want the widget to fill all available space horizontally:

```ruby
require 'glimmer-dsl-swt'

class TaskTimer
  class Task
    attr_accessor :name, :elapsed_time

    def initialize(name)
      @name = name
      @elapsed_time = 0
    end
  end

  include Glimmer::UI::CustomShell

  before_body do
    @tasks = [Task.new('Test')]
  end

  body {
    shell {
      grid_layout {
        num_columns 2
        make_columns_equal_width false
      }

      @tasks.each do |task|
        radio {
          text task.name
        }

        label {
          layout_data :fill, :center, true, false
          text <= [task, :elapsed_time]
        }
      end

      @current_thread = Thread.new do
        loop {
          @tasks[0].elapsed_time += 1
          puts @tasks[0].elapsed_time
          sleep(1)
        }
      end
    }
  }
end

TaskTimer.launch
```

![Screen Shot 2021-11-26 at 3 38 31 PM](https://user-images.githubusercontent.com/23052/143631480-ab16d3b6-b5ce-4c20-b595-3e80c053c738.png)

![Screen Shot 2021-11-26 at 3 39 22 PM](https://user-images.githubusercontent.com/23052/143631544-92b41145-49f3-4a1e-81c6-b8b9ad08cd8f.png)

I just updated the docs again to make even clearer.

Here is my explanation under the Layouts section:
https://github.com/AndyObtiva/glimmer-dsl-swt/blob/master/docs/reference/GLIMMER_GUI_DSL_SYNTAX.md#layouts

Specifically, this bit:
"Note that if you need to have widgets fill a `row_layout` and resize automatically upon window resize, you must nest `fill true` within. This is the automatic behavior of `fill_layout`. For `grid_layout`, you would have to add `layout_data :fill, :center, true, false` to a child that you want to fill all the available space horizontally initially and after window resize.

Do not be alarmed if widget sizes were kept fixed on resize of a window. This is normal behavior that can always be overridden with options, such as fill true mentioned above. You need to learn more about each layout before you have mastered them enough to do anything you want with layouts."
